import type { HistorySlot, QueueSlot } from "~/clients/backend-client.server";

/** DEV-only sample rows for `/queue?preview=1`. */
export const PREVIEW_QUEUE_SLOTS: QueueSlot[] = [
  {
    nzo_id: "preview-q-1",
    priority: "0",
    filename: "Severance.S02E03.2160p.WEB-DL.DDP5.1.Atmos.H.265-FLUX.mkv",
    cat: "tv",
    percentage: "62",
    true_percentage: "62",
    status: "Downloading",
    mb: "8420",
    mbleft: "3199",
    indexer: "NZBgeek",
    providers: [
      { host: "news.eweka.nl", nickname: "Eweka", segments: 410 },
      { host: "news.newshosting.com", nickname: "Newshosting", segments: 92 },
    ],
  },
  {
    nzo_id: "preview-q-2",
    priority: "0",
    filename: "The.Brutalist.2024.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-FLUX.mkv",
    cat: "movies",
    percentage: "0",
    true_percentage: "0",
    status: "Queued",
    mb: "22140",
    mbleft: "22140",
    indexer: "DOGnzb",
    providers: [],
  },
  {
    nzo_id: "preview-q-3",
    priority: "-1",
    filename: "Silo.S02E07.1080p.WEB-DL.DDP5.1.H.264-NTb.mkv",
    cat: "tv",
    percentage: "0",
    true_percentage: "0",
    status: "Paused",
    mb: "1860",
    mbleft: "1860",
    indexer: "NZBgeek",
    providers: [],
  },
];

export const PREVIEW_HISTORY_SLOTS: HistorySlot[] = [
  {
    nzo_id: "preview-h-1",
    nzb_name: "Andor.S02E12.2160p.WEB-DL.DDP5.1.Atmos.H.265-NTb.nzb",
    name: "Andor.S02E12.2160p.WEB-DL.DDP5.1.Atmos.H.265-NTb.mkv",
    category: "tv",
    status: "Completed",
    bytes: 8_420_000_000,
    storage: "/content/tv/Andor/Season 02",
    download_time: 412,
    completed: Math.floor(Date.now() / 1000) - 40 * 60,
    fail_message: "",
    nzb_blob_id: "preview-blob-1",
    indexer: "NZBgeek",
    providers: [{ host: "news.eweka.nl", nickname: "Eweka", segments: 800 }],
  },
  {
    nzo_id: "preview-h-2",
    nzb_name: "Dune.Part.Two.2024.2160p.UHD.BluRay.DDP5.1.DV.H.265-FLUX.nzb",
    name: "Dune.Part.Two.2024.2160p.UHD.BluRay.DDP5.1.DV.H.265-FLUX.mkv",
    category: "movies",
    status: "Completed",
    bytes: 42_100_000_000,
    storage: "/content/movies/Dune Part Two (2024)",
    download_time: 1802,
    completed: Math.floor(Date.now() / 1000) - 3 * 60 * 60,
    fail_message: "",
    nzb_blob_id: "preview-blob-2",
    indexer: "DOGnzb",
    providers: [{ host: "news.newshosting.com", nickname: "Newshosting", segments: 1200 }],
  },
  {
    nzo_id: "preview-h-3",
    nzb_name: "The.Bear.S03E01.1080p.WEB-DL.DDP5.1.H.264-NTb.nzb",
    name: "The.Bear.S03E01.1080p.WEB-DL.DDP5.1.H.264-NTb.mkv",
    category: "tv",
    status: "Failed",
    bytes: 1_540_000_000,
    storage: "",
    download_time: 88,
    completed: Math.floor(Date.now() / 1000) - 26 * 60 * 60,
    fail_message: "Article with message-id <preview@usenet> is missing",
    nzb_blob_id: "preview-blob-3",
    indexer: "NZBgeek",
    providers: [],
  },
  {
    nzo_id: "preview-h-4",
    nzb_name: "Shogun.S01E10.2160p.WEB-DL.DDP5.1.H.265-FLUX.nzb",
    name: "Shogun.S01E10.2160p.WEB-DL.DDP5.1.H.265-FLUX.mkv",
    category: "tv",
    status: "Completed",
    bytes: 9_120_000_000,
    storage: "/content/tv/Shogun/Season 01",
    download_time: 640,
    completed: Math.floor(Date.now() / 1000) - 2 * 24 * 60 * 60,
    fail_message: "",
    nzb_blob_id: "preview-blob-4",
    indexer: "NZBgeek",
    providers: [{ host: "news.eweka.nl", nickname: "Eweka", segments: 900 }],
  },
];
